name: widgetx
description: Superpowers for your flutter widgets. Collection of useful extensions on Flutter's Widget Kit.
version: 0.1.1
homepage: https://github.com/ishaan1995/widgetx

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
